# Tags

[awesome_open_source]
link = 'https://www.youtube.com/@AwesomeOpenSource'
name = 'Awesome Open Source Youtube Channel'

[techno_tim]
link = ''
name = 'Techno Tim Youtube Channel'

[christian_lempa]
link = ''
name = 'Christian Lempa youtube channel'
